name: BrowserProxy-compile

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18.2
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.2
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: |
          cd ./server
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w --extldflags "-static -fpic"' .

      - name: Copy files
        run: |
          mkdir ./artifacts
          mv ./server/server ./server/BrowserProxy
          cp ./server/BrowserProxy ./artifacts
          cp ./server/config.ini ./artifacts
          cp ./server/sshlist.json ./artifacts
          chmod -R 777 ./artifacts
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: BrowserProxy-linux-amd64
          path: /home/runner/work/BrowserProxy/BrowserProxy/artifacts
